### ISSUE TITLE
Status/Future of this Repository

### ISSUE THREAD

**Issue by gakonst** [rust-blockchain/evm#56]
As far as I can tell, there's a few useful PRs that are sort of stalled, and also it seems like there's no consistent release process. I wonder if there's any specific plans around how this EVM implementation will be expanded over time, or if it's worth figuring out additional people that'd be able to review/merge PRs & publish?

**Comment by sorpaas** [comment]
Not sure why you got the impression that this project is stalled -- it's definitely not!

This is actively being used in the Frontier project -- Substrate's Ethereum compatibility layer. NEAR is also using it for their EVM engines.

I'm going to close this issue since the rest of question -- regarding the roadmap -- is to broad. For anything please feel free to open specific issue (like London support, for example), if you are interested in tracking the progress.

**Comment by joshuajbouw** [comment]
Feel free to join the conversation: https://matrix.to/#/#evm:matrix.org

**Comment by gakonst** [comment]
Ah! My apologies for this. Will join the Matric chat.
